spring.application.name=UserService
server.port=5000
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://userservice-instance.czs2y4aqogqj.ap-south-1.rds.amazonaws.com:3306/userservice
spring.datasource.username=admin
spring.datasource.password=Scalar123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/user_service
#spring.datasource.username=jaya_user
##spring.datasource.password=password
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql= true

#userservice-instance.czs2y4aqogqj.ap-south-1.rds.amazonaws.com